### ISSUE TITLE
didn't work if favicon

### ISSUE THREAD

**Issue by unknownuser88** [gamcoh/QuickEdit#1]
if I have favicon `<link rel="shortcut icon" type="image/png" href="favicon.png"/>`
it gives me an error on console

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "QuickEdit in /path to sublime/Installed Packages/QuickEdit.sublime-package", line 63, in run
FileNotFoundError: [Errno 2] No such file or directory: '/path to folder/favicon.png'
```

in this case `<link rel="icon" type="image/vnd.microsoft.icon" href="favicon.ico"/>`
error is following:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "QuickEdit in /path to sublime/Installed Packages/QuickEdit.sublime-package", line 63, in run
  File "./python3.3/codecs.py", line 313, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 30: invalid start byte
```

**Comment by gamcoh** [comment]
I just fixed this issu
